outdir: runs/template-dual-circuit

base:
  Ny: 100
  Nx: 100
  steps: 5000
  dt: 0.01
  dx: 1.0
  save_every: 200
  stopping_threshold: 0.0001
  min_steps: 500
  init_mode: all_off
  activator_type1: juxtacrine
  activator_type2: juxtacrine
  spike_value: 2.0
  n_points: 10
  nucleation_rate: 0.01

  p1:
    act_half_sat: 1.0
    inh_half_sat: 1.0
    act_decay_rate: 1.0
    basal_prod: 0.0
    act_diffusion: 1.0
    inh_diffusion: 20.0
    act_prod_rate: 15.0
    inh_prod_rate: 8.0
    inh_decay_rate: 0.5
    cross_inhibition_rate: 0.0
    act_hill_coeff: 4
    inh_hill_coeff: 4

  p2:
    act_half_sat: 1.0
    inh_half_sat: 1.0
    act_decay_rate: 1.0
    basal_prod: 0.0
    act_diffusion: 1.0
    inh_diffusion: 20.0
    act_prod_rate: 7.0
    inh_prod_rate: 25.0
    inh_decay_rate: 0.5
    cross_inhibition_rate: 0.0
    act_hill_coeff: 10
    inh_hill_coeff: 4

mode: zip
sweeps:
  p1:
    cross_inhibition_rate: [0, 2.0, 4]
  p2:
    cross_inhibition_rate: [0, 6.25, 12.5]
