outdir: runs/fig1c-sweep

base:
  Nx: 100
  Ny: 100
  steps: 50000
  dt: 0.01
  dx: 1.0
  save_every: 200
  stopping_threshold: 0.0001
  min_steps: 1000

  activator_type: juxtacrine
  spike_value: 5.0
  nucleation_rate: 0.0

  act_decay_rate: 1.0
  act_half_sat: 1.0
  inh_half_sat: 1.0
  basal_prod: 0.0

  act_hill_coeff: 3
  inh_hill_coeff: 3

  act_prod_rate: 5.0
  inh_decay_rate: 0.5

  act_diffusion: 1.0
  inh_diffusion: 10.0

mode: grid
sweeps:
  inh_prod_rate: [1, 3, 5, 12, 14]
